#ifndef MOEGAMEENGINE_GLOBAL_H
#define MOEGAMEENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MOEGAMEENGINE_LIBRARY)
#  define MOEGAMEENGINE_EXPORT Q_DECL_EXPORT
#else
#  define MOEGAMEENGINE_EXPORT Q_DECL_IMPORT
#endif

#endif // MOEGAMEENGINE_GLOBAL_H
